---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: arbeidssokerregistrering
  namespace: default
  labels:
    team: paw
spec:
  env:
  - name: APPRES_CMS_URL
    value: https://appres.nav.no
  - name: LOGINSERVICE_URL
    value: https://loginservice.nav.no/login
  - name: AAD_B2C_CLIENTID_USERNAME
    value: 45104d6a-f5bc-4e8c-b352-4bbfc9381f25
  - name: AAD_B2C_DISCOVERY_URL
    value: https://login.microsoftonline.com/navnob2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten
  - name: ARBEIDSSOKERREGISTRERING_URL
    value: https://arbeidssokerregistrering.nav.no
  - name: DITTNAV_LINK_URL
    value: https://tjenester.nav.no/dittnav/
  - name: VEIENTILARBEID_URL
    value: https://veientilarbeid.nav.no
  - name: SYKEFRAVAER_URL
    value: https://tjenester.nav.no/sykefravaer
  - name: AKTIVITETSPLAN_URL
    value: https://aktivitetsplan.nav.no
  - name: PAM_JANZZ_URL
    value: https://pam-janzz.nais.oera.no
  image: docker.adeo.no:5000/fo/arbeidssokerregistrering
  ingresses:
  - https://arbeidssokerregistrering.nais.oera.no
  - https://arbeidssokerregistrering.nav.no/
  liveness:
    path: /internal/isAlive
    port: 8080
  port: 8080
  prometheus:
    enabled: true
    path: /internal/metrics
  readiness:
    path: /internal/isReady
    port: 8080
    initialDelay: 15
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      memory: 512Mi
  webproxy: true
