---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: arbeidssokerregistrering
  namespace: default
  labels:
    team: paw
spec:
  env:
  - name: CONFIGURATION_LOCATION
    value: /decorator-fss.yaml
  - name: DISABLE_DECORATOR
    value: "true"
  - name: UNLEASH_API_URL
    value: https://unleash.nais.adeo.no/api/
  - name: VEILARBPERSONFLATEFS_URL
    value: https://app-q0.adeo.no/veilarbpersonflatefs/
  - name: VEILARBOPPFOLGINGAPI_URL
    value: https://veilarboppfolging-q0.nais.preprod.local/veilarboppfolging/api
  - name: VEILARBPERSONAPI_URL
    value: https://veilarbperson-q0.nais.preprod.local/veilarbperson/api
  - name: AKTOERREGISTER_API_V1_DESCRIPTION
    value: Versjon 1 av REST-API for aktoerregisteret
  - name: AKTOERREGISTER_API_V1_URL
    value: https://app-q0.adeo.no/aktoerregister/api/v1
  image: docker.adeo.no:5000/fo/arbeidssokerregistrering
  ingresses:
  - https://arbeidssokerregistrering.nais.preprod.local
  - https://arbeidssokerregistrering-q.nav.no/
  liveness:
    path: /internal/isAlive
    port: 8080
  port: 8080
  prometheus:
    enabled: true
    path: /internal/metrics
  readiness:
    path: /internal/isReady
    port: 8080
    initialDelay: 15
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      memory: 512Mi
