const texts = {
    "nb": {
        "allerede-registrert-boks-1-knapp": "Aktivitetsplan",
        "allerede-registrert-boks-1-lenke": "/aktivitetsplan/",
        "allerede-registrert-boks-1-tekst": "Du kan fortsette med Aktivitetsplanen.",
        "allerede-registrert-boks-2-knapp": "Veien til arbeid",
        "allerede-registrert-boks-2-lenke": "/veientilarbeid/",
        "allerede-registrert-boks-2-tekst": "Du kan finne informasjon i Veien til arbeid.",
        "allerede-registrert-boks-3-knapp": "Dialog",
        "allerede-registrert-boks-3-lenke": "/aktivitetsplan/dialog/ny/",
        "allerede-registrert-boks-3-tekst": "Du kan kontakte ditt lokale NAV-kontor.",
        "allerede-registrert-panel-dagpenger-tekst": "Hvis du ønsker å søke dagpenger, må du først ta kontakt med NAV. \nRing oss på 55 55 33 33 med tastevalg 2.",
        "allerede-registrert-panel-dagpenger-tittel": "Ønsker du å søke dagpenger?",
        "allerede-registrert-tittel": "Du er allerede registrert hos NAV",
        "allerede-registrert-undertittel": "Hva nå?",
        "allerede-registrert-fss-lenke": "Gå til Aktivitetsplanen",
        "allerede-registrert-fss-melding": "Brukere som er registrert som arbeidssøkere og som er under arbeidsrettet oppfølging får en egen aktivitetsplan.",
        "allerede-registrert-fss-tittel": "Aktivitetsplan",
        "avbryt-beskrivelse-registrering": "Er du sikker på at du vil avbryte registreringen?",
        "avbryt-beskrivelse-sykmeldt": "Er du sikker på at du vil avbryte?",
        "banner-overskrift-ordinaer-manuell": "Registrering av arbeidssøker",
        "banner-overskrift-ordinaer": "Registrering",
        "banner-overskrift-registrering-av-arbeidssoker": "Registrering av arbeidssøker",
        "banner-overskrift-sykefravaer-manuell": "Start arbeidsrettet oppfølging av sykmeldt bruker",
        "banner-overskrift-sykefravaer": "Mer veiledning fra NAV",
        "banner-fss-bruker-allerede-registrert": "Brukeren er allerede registrert hos NAV",
        "datepicker-historisk-dato": "dato er frem i tid",
        "datepicker-ugyldig-dato": "ugyldig dato",
        "datepicker.forrige-maaned": "forrige måned",
        "datepicker.neste-maaned": "neste måned",
        "avbryt-lenke-registrering": "Avbryt registreringen",
        "avbryt-lenke-sykmeldt": "Avbryt",
        "avbryt-lenke": "Avbryt",
        "beskrivelse-registrerdeg": "Når du registrerer deg får flere fordeler:",
        "beskrivelse-registrering-pc": "Resten av registreringen er ikke tilpasset din mobil. Vi anbefaler deg derfor å fortsette registreringen på en PC.",
        "knapp-avbryt": "Avbryt",
        "knapp-enig": "ENIG",
        "knapp-ja-avbryt": "Ja, avbryt",
        "knapp-logg-inn": "Logg inn",
        "knapp-nei": "Nei",
        "knapp-neste": "Neste",
        "knapp-registrerdeg": "Start registrering",
        "knapp-sbl-registrering-avbryt": "Avbryt",
        "knapp-sbl-registrering-neste": "Neste",
        "knapp-tilbake": "Tilbake",
        "knapp-uenig": "UENIG",
        "liste-arbeidsgiverefinner": "arbeidsgivere finner deg i CV-basen vår",
        "liste-dufarhjelp": "du får hjelp til å komme i jobb",
        "liste-dukanabonnere": "du kan abonnere på ledige stillinger",
        "liste-dukansoke": "du kan søke om dagpenger eller annen økonomisk støtte",
        "nei": "Nei",
        "overskrift-registrerdeg": "Registrer deg som arbeidssøker",
        "overskrift-registrering-pc": "Du bør fortsette registreringen på PC",
        "tekst-dittnav": "Gå til Ditt NAV",
        "tekst-gaatilforside": "Gå til forside nav.no",
        "tips-fullforregistrering": "Tips: Fullfør registrering først, så kan du søke om dagpenger.",
        "duernaregistrert-knapp-ikke-na": "Skal ikke søke nå",
        "duernaregistrert-knapp-ja": "Søk dagpenger",
        "duernaregistrert-knapp-les-mer": "Les mer",
        "duernaregistrert-knapp-sok-dagpenger": "Søk dagpenger",
        "duernaregistrert-manuell-innholdstittel": "Brukeren er registrert",
        "duernaregistrert-manuell-lenke-videre": "Vis registrert informasjon",
        "duernaregistrert-manuell-normaltekst": "Du tas nå automatisk videre til den registrerte informasjonen",
        "duernaregistrert-ordinaer-element": "Ønsker du å søke dagpenger nå?",
        "duernaregistrert-ordinaer-innholdstittel": "Du er nå registrert som arbeidssøker",
        "duernaregistrert-ordinaer-normaltekst": "<p>Er du permittert eller arbeidsledig må du søke om dagpenger i egen søknad.</p> \n<p>Du kan tidligst få dagpenger fra den dagen du sender søknaden.</p>\n<p>For å ikke tape dager med dagpenger må du sende søknaden senest samme dag som du ønsker dagpenger fra.</p>",
        "duernaregistrert-ordinaer-systemtittel": "Har du søkt om dagpenger?",
        "duernaregistrert-sykmeldt-element": "Vil du se mer infomasjon om videre økonomisk støtte?",
        "duernaregistrert-sykmeldt-innholdstittel": "Du kan nå få mer veiledning",
        "duernaregistrert-sykmeldt-normaltekst": "Hvis du skal søke om økonomisk støtte etter at retten til sykepenger tar slutt, må du gjøre det i en egen søknad.",
        "duernaregistrert-sykmeldt-systemtittel": "Videre støtte etter sykepenger",
        "feilhandtering-ikke-tilgang-aareg": "Det har skjedd en feil i systemet. Årsak til feilen kan være manglende lesetilgang til AA registret.\nTa kontakt med din lokale identansvarlige. Hvis feilen fortsatt vedvarer, ta kontakt med <a href=\"https://www.nav.no/no/nav-og-samfunn/kontakt-nav/relatert-informasjon/kontakt-teknisk-brukerstotte-nav.no\">teknisk brukerstøtte</a>.",
        "feilhandtering-mangler-arb-tillatelse-overtekst": "Det er registrert at du mangler arbeidstillatelse. Du kan derfor ikke registrere deg som arbeidssøker.",
        "feilhandtering-overtekst": "På grunn av feil i systemene våre kan du ikke registrere deg akkurat nå.",
        "feilhandtering-undertekst": "Hvis det ikke stemmer, kontakt <a href=\"https://www.nav.no/no/nav-og-samfunn/kontakt-nav/relatert-informasjon/kontakt-teknisk-brukerstotte-nav.no\">teknisk brukerstøtte</a>.",
        "feilhandtering-utvandret-overtekst": "Du er registrert som utvandret og kan derfor ikke registrere deg som arbeidssøker.",
        "feilmelding-generell": "På grunn av feil i systemene våre kan du ikke registrere deg akkurat nå.<br/><br/>\nVennligst prøv igjen litt senere.<br /><br/>\n<a href=\"https://www.nav.no/no/nav-og-samfunn/kontakt-nav/teknisk-brukerstotte/kontakt-teknisk-brukerstotte-nav.no\">Kontakt teknisk brukerstøtte</a> dersom problemene vedvarer.",
        "enhet-mangler": "Enhet magler i kontekst",
        "feil-i-systemene-beskrivelse": "På grunn av en feil er ikke tjenesten tilgjengelig akkurat nå. Vennligst prøv igjen senere",
        "fnr-mangler": "Du må søke opp en person for å kunne registrere arbeidssøker",
        "oops-feilmelding-beskrivelse": "Siden eller tjenesten er for tiden utilgjengelig på grunn av teknisk feil. <br> Vi beklager dette. Prøv igjen senere.",
        "oops-feilmelding-header": "Oops, noe gikk galt",
        "oops-feilmelding-kontakt": "NAV Kontaktsenter 55 55 33 33, hverdager 08.00-15.30 <br> Hjelpemidler, bil og tolk 55 55 33 35 <br> Arbeidsgivertelefonen 55 55 33 36 <br> Pensjon 55 55 33 34",
        "oops-feilmelding-lenker": "Oops, noe gikk galt",
        "fullfor-advarsel": "Du må huke av at du har lest og forstått kravene for å kunne fullføre registreringen.",
        "fullfor-header": "Fullfør registreringen",
        "fullfor-knapp": "Fullfør",
        "fullfor-les-mer-CV": "Når du fullfører registreringen, vil du få en oppgave i aktivitetsplanen om at du må fylle ut CV-en din. Det er viktig at du holder CV-en din oppdatert slik at du er synlig for arbeidsgivere.",
        "fullfor-les-mer-aktivitetsplan": "I aktivitetsplanen kan du holde orden på aktiviteter du gjør i samarbeid med NAV. Du kan også kommunisere med veilederen din. Når du fullfører registreringen, vil det ligge oppgaver til deg i aktivitetsplanen.",
        "fullfor-les-mer-meldekort": "For å få oppfølging og støtte må du hver 14. dag melde fra at du fortsatt ønsker å være registrert som arbeidssøker. Dette gjør du ved å sende meldekort. Sender du meldekort for sent, kan det føre til at utbetalingen din blir redusert eller stanset.",
        "fullfor-les-mer-okonomi": "Hvis du skal søke om dagpenger eller annen støtte fra NAV, må du gjøre det i en egen søknad etter at du har fullført registreringen. For å motta støtte, må du oppfylle kravene NAV stiller.",
        "fullfor-les-mer": "Les mer om kravene",
        "fullfor-liste-1": "sende meldekort hver 14. dag",
        "fullfor-liste-2": "registrere CV-en din og holde den oppdatert",
        "fullfor-liste-3": "være en aktiv jobbsøker",
        "fullfor-liste-4": "bruke aktivitetsplanen din",
        "fullfor-overskrift-liste": "Når du fullfører, godtar du kravene under fra NAV. Du må",
        "fullfor-sjekkboks": "Jeg har lest og forstått kravene",
        "info-for-ikke-arbeidssoker-uten-oppfolging-innhold": "Du er sykmeldt i følge våre systemer. Hvis du ønsker å registrere deg, må du ringe 55 55 33 39, tastevalg 3.",
        "infoside-knapp-enig": "Enig",
        "infoside-knapp-uenig": "Uenig, jeg trenger mer veiledning",
        "infoside-tilbake-full-stilling-info": "Hvis situasjonen din endrer seg, er det viktig at du tar kontakt med veilederen din.",
        "infoside-tilbake-full-stilling-tekst-1": "har du ikke rett til videre økonomisk støtte fra NAV etter at du er tilbake i jobb",
        "infoside-tilbake-full-stilling-tekst-2": "tror vi ikke du trenger mer veiledning fra NAV i tillegg til det du allerede har fått og får i dag",
        "infoside-tilbake-full-stilling-tittel": "Fordi du skal tilbake i full jobb innen 52 uker",
        "infoside-trenger-plan-tittel": "Er du enig i NAV sin vurdering over?",
        "infoside-veilederpanel-tekst": "På spørsmål om hva du mener er din fremtidige situasjon, har du svart at du skal tilbake i full jobb før du har vært sykmeldt i 52 uker.",
        "infoside-veilederpanel-tittel": "Hei, {fornavn}",
        "ja": "Ja",
        "krever-reaktivering-boks-tekst": "Hvis du fortsatt skal motta ytelser må du først bekrefte at du ønsker å være registrert, så søke på nytt.",
        "krever-reaktivering-tittel": "Du er ikke lenger registrert som arbeidssøker",
        "krever-reaktivering-undertittel": "Ønsker du å være registrert som arbeidssøker?",
        "lenke-neste": "Neste",
        "finn-ditt-nav-kontor-lenke-url": "https://www.nav.no/person/personopplysninger#ditt-nav-kontor",
        "oppsummering-andreforhold-svar-ja": "Du trenger oppfølging i forbindelse med andre utfordringer",
        "oppsummering-andreforhold-svar-nei": "Du trenger ikke oppfølging i forbindelse med andre utfordringer",
        "oppsummering-dinsituasjon-svar-akkurat-fullfort-utdanning": "Du har akkurat fullført utdanning, militærtjeneste eller annet",
        "oppsummering-dinsituasjon-svar-aldri-hatt-jobb": "Du har aldri vært i jobb",
        "oppsummering-dinsituasjon-svar-deltidsjobb-vil-mer": "Du har deltidsjobb, men vil jobbe mer",
        "oppsummering-dinsituasjon-svar-er-permittert": "Du er permittert eller vil bli permittert",
        "oppsummering-dinsituasjon-svar-har-sagt-opp": "Du har sagt opp eller kommer til å si opp",
        "oppsummering-dinsituasjon-svar-jobb-over-2-aar": "Du har ikke vært i jobb de siste 2 årene",
        "oppsummering-dinsituasjon-svar-mistet-jobben": "Du har mistet eller kommer til å miste jobben",
        "oppsummering-dinsituasjon-svar-usikker-jobbsituasjon": "Du er usikker på situasjonen din",
        "oppsummering-dinsituasjon-svar-vil-bytte-jobb": "Du har jobb, men vil bytte",
        "oppsummering-dinsituasjon-svar-vil-fortsette-i-jobb": "Du har jobb og ønsker å fortsette i den jobben du er i",
        "oppsummering-dinsituasjon": "Du registrerer deg fordi:",
        "oppsummering-fremtidigsituasjon-svar-ingen-passer": "PLACEHOLDER: INGEN PASSER",
        "oppsummering-fremtidigsituasjon-svar-ny-arbeidsgiver": "PLACEHOLDER: NY ARBEIDSGIVER",
        "oppsummering-fremtidigsituasjon-svar-samme-arbeidsgiver-ny-stilling": "Du skal tilbake til nåværende arbeidsgiver i en ny stilling",
        "oppsummering-fremtidigsituasjon-svar-samme-arbeidsgiver": "Du skal tilbake til nåværende arbeidsgiver i en redusert stilling",
        "oppsummering-fremtidigsituasjon-svar-usikker": "PLACEHOLDER: USIKKER",
        "oppsummering-helsehinder-svar-ja": "Du trenger oppfølging i forbindelse med helseutfordringer",
        "oppsummering-helsehinder-svar-nei": "Du trenger ikke oppfølging i forbindelse med helseutfordringer",
        "oppsummering-andre-forhold-fortekst": "Andre problemer:",
        "oppsummering-helse-hinder-fortekst": "Helseproblemer:",
        "oppsummering-sistestilling-fortekst": "Siste stilling:",
        "oppsummering-situasjon-fortekst": "Situasjon:",
        "oppsummering-utdanning-bestatt-fortekst": "Utdanning bestått:",
        "oppsummering-utdanning-fortekst": "Høyeste fullførte utdanning:",
        "oppsummering-utdanning-godkjent-fortekst": "Utdanning godkjent i Norge:",
        "ordinaer-oppsummering-ingress": "Her er opplysningene vi har registrert om deg.",
        "ordinaer-oppsummering-knapp-riktig": "Ja, riktig",
        "ordinaer-oppsummering-tittel": "Er opplysningene riktige?",
        "oppsummering-arbeidserfaring-1": "Ifølge Arbeidsgiver- og arbeidstakerregisteret har du vært i jobb i løpet av det siste året. Hvis det er feil, er det likevel viktig at du fullfører registreringen. Du kan gi riktig informasjon senere til NAV.",
        "oppsummering-arbeidserfaring-2": "Ifølge Arbeidsgiver- og arbeidstakerregisteret har du ikke vært i jobb i løpet av det siste året. Hvis det er feil, er det likevel viktig at du fullfører registreringen. Du kan gi riktig informasjon senere til NAV.",
        "sykmeldt-oppsummering-andre-hensyn-fortekst": "Andre hensyn NAV bør ta:",
        "sykmeldt-oppsummering-besvarelser-info": "Hvis noen av opplysningene ikke stemmer, kan du informere veilederen din etter at du har fullført.",
        "sykmeldt-oppsummering-egress": "Når du fullfører, deler du opplysningene med veilederen din.",
        "sykmeldt-oppsummering-framtidig-situasjon-fortekst": "Fremtidig situasjon:",
        "sykmeldt-oppsummering-ingress": "Vi har registrert disse opplysningene om deg:",
        "sykmeldt-oppsummering-knapp-fullfor": "Fullfør",
        "sykmeldt-oppsummering-sykepenger-frem-til": "Sykepenger frem til:",
        "sykmeldt-oppsummering-tilbake-i-jobb-fortekst": "Tilbake innen 52 uker uker:",
        "sykmeldt-oppsummering-tittel": "Dine opplysninger",
        "oppsummering-utdanningbestatt-svar-ja": "Utdanningen din er bestått",
        "oppsummering-utdanningbestatt-svar-nei": "Utdanningen din er ikke bestått",
        "oppsummering-utdanninggodkjent-svar-ja": "Utdanningen din er godkjent i Norge",
        "oppsummering-utdanninggodkjent-svar-nei": "Utdanningen din er ikke godkjent i Norge",
        "oppsummering-utdanninggodkjent-svar-vet-ikke": "Vet ikke om utdanningen er godkjent i Norge",
        "beskrivelse-regvellykket": "Du har nå fullført registrering som arbeidssøker hos NAV.",
        "overskrift-regvellykket": "Din registrering er vellykket!",
        "skjema.alternativ.advarsel.tekst": "Du må svare på spørsmålet før du kan gå videre.",
        "andreforhold-info-registrering": "Svarer du ja, kan du fortelle mer til en veileder i en oppfølgingssamtale. Vi kontakter deg når du har registrert deg.",
        "andreforhold-info-sykmeldt": "Svarer du ja, kan du fortelle mer til NAV-veilederen som tar kontakt med deg.",
        "andreforhold-ingress-registrering": "For eksempel språk, lesing og skriving eller familiesituasjon.",
        "andreforhold-ingress-sykmeldt": "For eksempel språk, lesing og skriving eller familiesituasjon",
        "andreforhold-svar-ja": "Ja",
        "andreforhold-svar-nei": "Nei",
        "andreforhold-tittel-registrering": "Har du andre problemer med å søke eller være i jobb?",
        "andreforhold-tittel-sykmeldt": "Er det noe annet enn helsen din som NAV bør ta hensyn til?",
        "dinsituasjon-svar-akkurat-fullfort-utdanning": "Har akkurat fullført utdanning, militærtjeneste eller annet",
        "dinsituasjon-svar-aldri-hatt-jobb": "Har aldri vært i jobb",
        "dinsituasjon-svar-deltidsjobb-vil-mer": "Har deltidsjobb, men vil jobbe mer",
        "dinsituasjon-svar-er-permittert": "Er permittert eller kommer til å bli permittert",
        "dinsituasjon-svar-har-sagt-opp": "Har sagt opp eller kommer til å si opp",
        "dinsituasjon-svar-jobb-over-2-aar": "Har ikke vært i jobb de siste 2 årene",
        "dinsituasjon-svar-mistet-jobben": "Har mistet eller kommer til å miste jobben",
        "dinsituasjon-svar-usikker-jobbsituasjon": "Er usikker på jobbsituasjonen min",
        "dinsituasjon-svar-vil-bytte-jobb": "Har jobb, men vil bytte",
        "dinsituasjon-svar-vil-fortsette-i-jobb": "Har jobb og ønsker å fortsette i den jobben jeg er i",
        "dinsituasjon-tittel": "Velg den situasjonen som passer deg best",
        "fremtidigsituasjon-svar-ingen-passer": "Ingen av disse alternativene passer",
        "fremtidigsituasjon-svar-ny-arbeidsgiver": "Jeg trenger ny jobb",
        "fremtidigsituasjon-svar-samme-arbeidsgiver-ny-stilling": "Jeg skal tilbake til arbeidsgiveren min, men i ny stilling",
        "fremtidigsituasjon-svar-samme-arbeidsgiver": "Jeg skal tilbake til jobben jeg har",
        "fremtidigsituasjon-svar-usikker": "Jeg er usikker",
        "fremtidigsituasjon-tittel": "Hva tenker du om din fremtidige situasjon?",
        "helsehinder-info": "Svarer du ja, kan du fortelle mer til en veileder i en oppfølgingssamtale. Vi kontakter deg når du har registrert deg.",
        "helsehinder-svar-ja": "Ja",
        "helsehinder-svar-nei": "Nei",
        "helsehinder-tittel": "Har du helseproblemer som hindrer deg i å søke eller være i jobb?",
        "hvorlangtid-svar-kort-sikt": "Kort sikt",
        "hvorlangtid-svar-lang-sikt": "Lang sikt",
        "hvorlangtid-tittel": "Hvor lang tid?",
        "datepicker.feilmelding.egen.fradato-etter-frist": "Fra dato kan ikke være etter til dato",
        "siste-arbeidsforhold.arbeidsgiver": "Siste arbeidsgiver *",
        "siste-arbeidsforhold.fra-dato": "Fra dato *",
        "siste-arbeidsforhold.info.tekst": "Vi bruker opplysningene til å lage offentlig statistikk om arbeidsmarkedet. Hvis opplysningene er feil, kan du endre dem. Da får NAV riktigere statistikk. Vær oppmerksom på at opplysningene er hentet fra Arbeidsgiver- og arbeidstakerregisteret (Aa-registeret). Endrer du opplysninger hos NAV, blir de bare lagret hos oss. I Aa-registeret er det kun arbeidsgivere som kan endre.",
        "siste-arbeidsforhold.info.tittel": "Hva bruker vi informasjonen om din siste stilling til?",
        "siste-arbeidsforhold.ingress": "Følgende informasjon er registrert i Aa-registeret om din siste stilling: <br/> Hvis opplysningen er feil, kan du endre under.",
        "siste-arbeidsforhold.stilling": "Stilling *",
        "siste-arbeidsforhold.til-dato": "Til Dato",
        "siste-arbeidsforhold.undertittel": "Stilling",
        "siste-arbeidsgiver.feil.arbeidsgiver": "arbeidsgiver mangler",
        "siste-arbeidsgiver.feil.dato": "fra dato mangler",
        "siste-arbeidsgiver.feil.stilling": "stilling mangler",
        "siste-arbeidsgiver.feiloppsummering-tittel": "Du må fylle ut følgende felt:",
        "sistestilling-endre-tekst": "Endre",
        "sistestilling-svar-har-hatt-jobb": "Har vært i jobb",
        "sistestilling-svar-har-ikke-hatt-jobb": "Har ikke vært i jobb",
        "sistestilling-tittel": "Hva er din siste jobb?",
        "tilbakeiarbeid-svar-ja-full-stilling": "Ja, i full stilling",
        "tilbakeiarbeid-svar-ja-redusert-stilling": "Ja, i redusert stilling",
        "tilbakeiarbeid-svar-nei": "Nei",
        "tilbakeiarbeid-svar-usikker": "Usikker",
        "tilbakeiarbeid-tittel": "Tror du at du kommer tilbake i jobb før du har vært sykmeldt i 52 uker?",
        "utdanning-svar-grunnskole": "Grunnskole",
        "utdanning-svar-hoyere-utdanning-1-til-4": "Høyere utdanning (1 til 4 år)",
        "utdanning-svar-hoyere-utdanning-5-eller-mer": "Høyere utdanning (5 år eller mer)",
        "utdanning-svar-ingen-utdanning": "Ingen utdanning",
        "utdanning-svar-videregaende-fagbrev-svennebrev": "Videregående, fagbrev eller svennebrev (3 år eller mer)",
        "utdanning-svar-videregaende-grunnutdanning": "Videregående grunnutdanning (1 til 2 år)",
        "utdanning-tittel": "Hva er din høyeste fullførte utdanning?",
        "utdanningbestatt-svar-ja": "Ja",
        "utdanningbestatt-svar-nei": "Nei",
        "utdanningbestatt-tittel": "Er utdanningen din bestått?",
        "utdanninggodkjent-svar-ja": "Ja",
        "utdanninggodkjent-svar-nei": "Nei",
        "utdanninggodkjent-svar-vet-ikke": "Vet ikke",
        "utdanninggodkjent-tittel": "Er utdanningen din godkjent i Norge?",
        "registrering-arbeidssoker-avbyt-regitrering-fss": "Avbryt Registrering",
        "registrering-arbeidssoker-knapp-fss": "Start Registrering",
        "registrering-arbeidssoker-knapp": "Start Registrering",
        "registrering-arbeidssoker.argument1knapp": "Se video om aktivitetsplanen",
        "registrering-arbeidssoker.argument1tekst-fss": "<li>får du hjelp til å komme i jobb</li>\n<li>kan du søke om dagpenger eller annen økonomisk støtte</li>\n<li>vil arbeidsgivere finne deg i CV-basen vår</li>\n<li>kan du få varsler om ledige stillinger</li>\n<li>kan du bruke din egen aktivitetsplan</li>",
        "registrering-arbeidssoker.argument1tekst": "<li>får du hjelp til å komme i jobb</li>\n<li>kan du søke om dagpenger hvis du er permittert eller arbeidsledig</li>\n<li>kan du søke om annen økonomisk støtte</li>\n<li>kan du bruke din egen aktivitetsplan</li>",
        "registrering-arbeidssoker.argument2tekst1-fss": "<ul>\n    <li>Du har krav på at NAV vurderer behovet ditt for veiledning. Dette er en rettighet du har etter <a href=\"https://lovdata.no/NL/lov/2006-06-16-20/%C2%A714a\">NAV-loven § 14a</a>.</li>\n    <li>Du får et brev der du kan lese mer om tjenestene vi foreslår for deg.</li>\n</ul>",
        "registrering-arbeidssoker.argument2tekst1": "<ul>\n    <li>Du har krav på at NAV vurderer behovet ditt for veiledning. Dette er en rettighet du har etter <a class=\"lenke\" href=\"https://lovdata.no/NL/lov/2006-06-16-20/%C2%A714a\" target=\"_blank\">NAV-loven § 14a</a>.</li>\n    <li>Du får et brev der du kan lese mer om tjenestene vi foreslår for deg.</li>\n</ul>",
        "registrering-arbeidssoker.argument2tekst2-fss": "<ul>\n    <li>Du må sende meldekort hver 14. dag. Det er et krav for å få oppfølging og økonomisk støtte.</li>\n    <li>Du må være aktiv arbeidssøker, søke på ledige stillinger og holde CV-en oppdatert.</li>\n</ul>",
        "registrering-arbeidssoker.argument2tekst2": "<ul>\n    <li>Du må sende meldekort hver 14. dag. Det er et krav for å få oppfølging og økonomisk støtte.</li>\n    <li>Du må være aktiv arbeidssøker, søke på ledige stillinger og holde CV-en oppdatert.</li>\n</ul>",
        "registrering-arbeidssoker.argument2tittel1": "Rettigheter",
        "registrering-arbeidssoker.argument2tittel2": "Plikter",
        "registrering-arbeidssoker.argument3tittel-fss": "Dine opplysninger",
        "registrering-arbeidssoker.argument3tittel": "Dine opplysninger",
        "registrering-arbeidssoker.informasjon-modal.ingress": "<p>Aktivitetsplanen din er verktøyet du skal bruke for å komme i aktivitet og jobb. Denne blir delt med veilederen din. For at vi skal kunne følge deg opp best mulig, er det viktig at du bruker aktivitetsplanen aktivt. Du må gjennomføre de aktivitetene du avtaler med NAV i planen.</p>\n\n<p>Du kan selv legge inn og redigere målet ditt, aktiviteter du skal gjøre og stillinger du vil søke på. Du får også tilgang til en dialog der du kan kommunisere med veilederen din og diskutere aktiviteter du skal gjennomføre.</p>\n\n<p><b>Vi ønsker deg lykke til med jobbsøkingen!</b></p>",
        "registrering-arbeidssoker.informasjon-modal.innhold": "<ul class=\"typo-normal\">\n    <li>For at du skal holde oversikt og vite hva som forventes av deg, og kunne samarbeide med\n        veilederen din, har vi laget en aktivitetsplan på nav.no\n    </li>\n    <li>Aktivitetsplan er et verktøy du kan bruke for å komme deg ut i jobb, enten det er fort gjort\n        eller om det kreves litt mer langsiktig planlegging.\n    </li>\n    <li>Du setter deg mål, lager planer og legger inn oppgaver du skal gjennomføre.</li>\n    <li>Dette gjør du enkelt på små kort som du kan dra og slippe, avhengig av hva du har gjort så\n        langt.\n    </li>\n    <li>Og det fine er, at du kan dele alt med veilederen din så dere sammen kan diskutere det neste\n        steget ditt.\n    </li>\n    <li>Du og veilederen din samarbeider om aktivitetsplanen når dere møtes, og hver for dere.</li>\n    <li>Dere kan diskutere kortene og du får varsling når du har fått svar.</li>\n    <li>Målet er at du skal få en jobb på den måten som passer best for deg og din situasjon.</li>\n    <li>Lykke til!</li>\n</ul>",
        "registrering-arbeidssoker.informasjon-modal.tittel": "Hva er aktivitetsplanen?",
        "registrering-arbeidssoker.informasjon-modal.undertittel.skjul": "Skjul teksten for videoen",
        "registrering-arbeidssoker.informasjon-modal.undertittel": "Vis tekst for video",
        "registrering-arbeidssoker.introtittel": "Når du har registrert deg",
        "registrering-arbeidssoker.rad3.del1-fss": "NAV vurderer hva slags veiledning du trenger når du registrerer deg som jobbsøker. For å gjøre denne vurderingen må vi ha opplysninger om",
        "registrering-arbeidssoker.rad3.del1": "NAV vurderer hva slags veiledning du trenger når du registrerer deg som jobbsøker. For å gjøre denne vurderingen må vi ha opplysninger om",
        "registrering-arbeidssoker.rad3.del2-fss": "Vi har også opplysninger om arbeidssøkere i omtrent samme situasjon som deg. Det gjør at vi kan anta noe om mulighetene dine til å finne en jobb. På bakgrunn av dette blir det laget et automatisk forslag til hvilke tjenester vi tror kan passe for deg. En veileder vurderer forslaget og sender deg et vedtak i posten.",
        "registrering-arbeidssoker.rad3.del2": "Hvis det skjer endringer som gjør at opplysningene du har gitt oss ikke er riktige lenger, kan du ta kontakt med oss på\nnav.no. Da gjør vi en ny vurdering av ditt behov for tjenester.\n<br />\nVi har også opplysninger om arbeidssøkere i omtrent samme situasjon som deg.\nDet gjør at vi kan anta noe om mulighetene dine til å finne en jobb.\nPå bakgrunn av dette blir det laget et automatisk forslag til hvilke tjenester vi tror kan passe for deg.\nDette forslaget kaller vi profilering.\nEn veileder vurderer forslaget og sender deg et vedtak i posten.",
        "registrering-arbeidssoker.rad3.del3-innhold-fss": "Når du fullfører registreringen som arbeidssøker gjelder ikke samtykket du ga for å opprette CV og jobbprofil. CV-en og jobbprofilen blir tilgjengelig for veilederen som skal vurdere dine behov. Du må derfor endre opplysninger du ikke ønsker å dele på <a href=\"https://arbeidsplassen.nav.no/\">https://arbeidsplassen.nav.no/</a> før du starter registreringen.",
        "registrering-arbeidssoker.rad3.del3-tittel-fss": "Har du allerede registrert en CV eller jobbprofil på arbeidsplassen.nav.no?",
        "registrering-arbeidssoker.rad3.del4-innhold-fss": "Opplysningene dine blir lagret etter arkivloven. NAV bruker anonymiserte personopplysninger om arbeidssøkere til å lage offentlig statistikk om arbeidsmarkedet.\nLes mer om hvordan NAV behandler personopplysninger på <a href=\"https://www.nav.no/personvern\" target=\"_blank\">https://www.nav.no/personvern</a>.",
        "registrering-arbeidssoker.rad3.del4-tittel-fss": "Behandling av personopplysninger",
        "registrering-arbeidssoker.rad3.del4.innhold": "Opplysningene dine blir lagret  etter arkivloven.\nNAV bruker anonymiserte personopplysninger om arbeidssøkere til å\nlage offentlig statistikk om arbeidsmarkedet.",
        "registrering-arbeidssoker.rad3.del4.lenke": "NAV behandler personopplysninger",
        "registrering-arbeidssoker.rad3.del4.lesmer": "Les mer om hvordan",
        "registrering-arbeidssoker.rad3.del4.tittel": "Behandling av personopplysninger",
        "registrering-arbeidssoker.rad3.opplysninger-fss": "<ul>\n    <li>alderen din</li>\n    <li>du har vært i jobb</li>\n    <li>utdanningen din</li>\n    <li>eventuelle utfordringer</li>\n</ul>",
        "registrering-arbeidssoker.rad3.punkt1": "alderen din",
        "registrering-arbeidssoker.rad3.punkt2": "du har vært i jobb",
        "registrering-arbeidssoker.rad3.punkt3": "utdanningen din",
        "registrering-arbeidssoker.rad3.punkt4": "eventuelle utfordringer",
        "registrering-arbeidssoker.rad3.tips-fss": "<strong>Tips!</strong> Du må fullføre registreringen før du kan søke om dagpenger.",
        "registrering-arbeidssoker.registreringsknapp.url": "/start",
        "registrering-arbeidssoker.registreringsknapp": "Start registrering",
        "registrering-arbeidssoker.tipstekst": "<strong>Tips!</strong> Du må fullføre registreringen før du kan søke om dagpenger.",
        "registrering-arbeidssoker.tittel": "Registrer deg som arbeidssøker",
        "registrering-arbeidssoker.undertittel": "Det første du må gjøre når du mister jobben er å registrere deg",
        "registrering.personopplysninger.lenke": "Les mer om hvordan NAV behandler personopplysninger.",
        "registrering-arbeidssoker-rad2-del2-tittel-fss": "Har du allerede registrert en CV eller jobbprofil på arbeidsplassen.nav.no?",
        "registrering-sykemeldt-rad2-tekst1-fss": "Hvis du ønsker å registrere for mer veiledning, får du noen spørsmål om situasjonen din slik at du kan få riktig hjelp.\nDu kan endre på svarene hvis situasjonen din endrer seg.\nDet er bare veilederen din som kan se svarene dine.",
        "registrering-sykemeldt-rad2-tekst2-fss": "Samtykket du ga der, gjelder ikke her. Er det opplysninger du ikke ønsker å dele med veilederen, må du endre dem før du eventuelt registrerer deg for mer veiledning.",
        "registrering-sykemeldt-rad2-teskt2-tittel-fss": "Hvis du registrerer deg for mer veiledning fra NAV, vil veilederen din få se CV-en eller jobbprofilen som du har lagt inn på",
        "registrering-sykemeldt-rad2-tittle-fss": "Vil du registrere deg for å få mer veiledning fra NAV?",
        "registrering-sykemeldt.argument1tekst-fss": "<li>får du veiledning basert på behovene dine</li>\n<li>har du mulighet til å kommunisere direkte med veilederen din</li>\n<li>kan du bruke din egen aktivitetsplan</li>",
        "registrering-sykmeldt-knapp-fss": "Start Registrering",
        "registrering-sykmeldt-knapp": "Start Registrering",
        "registrering-sykmeldt-snakkeboble": "<strong>Hei, {fornavn}</strong> <p> Vi ser at du er sykmeldt, og at det begynner å nærme seg datoen du ikke lenger kan få sykepenger. </br> Tror du at du snart er tilbake i jobb, eller vil du trenge noe mer fra arbeidsgiveren din eller NAV?\n    </br> Hvis du trenger mer veiledning, må du registrere deg og svare på noen spørsmål.</p>",
        "registrering-sykmeldt.argument1knapp": "Se video om aktivitetsplanen",
        "registrering-sykmeldt.argument1tekst": "<li>får du veiledning om mulighetene dine</li>\n<li>kan du bruke din egen aktivitetsplan</li>\n<li>får du vite om du har krav på annen økonomisk støtte</li>\n<li>kan du ha dialog med veilederen din</li>",
        "registrering-sykmeldt.argument3tittel": "Registrer deg",
        "registrering-sykmeldt.introtittel": "Når du har registrert deg",
        "registrering-sykmeldt.rad3.del1-innhold-fss": "Når du registrerer deg for å få mer veiledning, skal NAV vurdere hva slags informasjon, veiledning og hjelp du trenger. Du vil derfor få noen spørsmål om situasjonen din slik at du kan få riktig hjelp. Du kan endre på svarene hvis situasjonen din endrer seg. Det er bare veilederen din som kan se hva du har svart. Opplysningene dine blir lagret etter arkivloven. Les mer om hvordan NAV behandler personopplysninger på <a href=\"https://www.nav.no/personvern\">https://www.nav.no/personvern</a>.",
        "registrering-sykmeldt.rad3.del1-tittel-fss": "Behandling av personopplysninger",
        "registrering-sykmeldt.rad3.del1": "Når du registrerer deg for å få mer veiledning, skal NAV vurdere hva slags informasjon, veiledning og hjelp du trenger. Du vil derfor få noen spørsmål om situasjonen din slik at du kan få riktig hjelp. Du kan endre på svarene hvis situasjonen din endrer seg. Det er bare veilederen din som kan se hva du har svart. Opplysningene dine blir lagret etter arkivloven. Les mer om <a class=\"lenke\" href=\"https://www.nav.no/no/NAV+og+samfunn/Om+NAV/personvern-i-arbeids-og-velferdsetaten\">hvordan NAV behandler personopplysninger</a>.",
        "registrering-sykmeldt.tittel": "Mer veiledning fra NAV",
        "beskrivelse-elektronisk-hjelp-stepup": "Hos ID-porten kan du skaffe deg elektronisk ID. Du kan velge mellom BankId, BankID på mobil, Buypass eller Commfides.",
        "beskrivelse-manuell-hjelp-stepup": "<p>Hvis du ikke kan skaffe deg elektronisk ID, må du møte opp på NAV-kontoret ditt. Der kan du få hjelp til å registere deg slik at du kan sende meldekort med MinID.</p>\n<p>Du kan finne ditt NAV kontor ved å søke på postnummer, poststed eller kommunenavn i søkefeltet.</p>",
        "manuell-hjelp-lenketekst": "Søk etter NAV kontor",
        "overskrift-elektronisk-hjelp-stepup": "Skaff deg elektronisk ID",
        "overskrift-hjelp-stepup": "Har du ikke elektronisk ID?",
        "overskrift-manuell-hjelp-stepup": "Registrer deg på NAV-kontoret",
        "overskrift-stepup": "Du må ha elektronisk ID for å registrere deg",
        "stepup-melding": "For å registrere deg hos NAV, må du logge inn med BankID, BankID på mobil, Buypass eller Commfides.",
        "uenig-selvgaende.angre": "ANGRE",
        "uenig-selvgaende.fortsett": "FORTSETT",
        "uenig-selvgaende.innhold": "Du har svart at du er uenig i at tjenesten passer for deg nå. Hvis du mener at du trenger annen tjeneste fra NAV for å komme i jobb, klikker du «Fortsett». Da må du starte registreringen på nytt i en annen tjeneste. Hvis du mener at tjenesten likevel passer for deg nå, klikker du «Angre».",
        "uenig-selvgaende.tittel": "Oppfølging fra NAV"
    }
};

export default texts;