kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: arbeidssokerregistrering
  namespace: {{namespace}}
  labels:
    team: paw
spec:
  env:
  - name: CONFIGURATION_LOCATION
    value: {{configuration_location}}
  - name: DISABLE_DECORATOR
    value: "true"
  - name: DISABLE_FRONTEND_LOGGER
    value: "true"
  - name: VEILARBPERSONFLATEFS_URL
    value: {{veilarbpersonflatefs_url}}
  - name: VEILARBOPPFOLGINGAPI_URL
    value: {{veilarboppfolging_url}}
  - name: VEILARBPERSONAPI_URL
    value: {{veilarbpersonapi_url}}
  - name: AKTOERREGISTER_API_V1_URL
    value: {{aktoerregister_api_v1_url}}
  - name: PAM_JANZZ_URL
    value: {{ pam_janzz_url }}
  image: {{ image }}
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  liveness:
    path: /internal/isAlive
    port: 8080
  port: 8080
  prometheus:
    enabled: true
    path: /internal/metrics
  readiness:
    path: /internal/isReady
    port: 8080
    initialDelay: 15
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "1"
      memory: 512Mi
