---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: arbeidssokerregistrering
  namespace: {{ namespace }}
  labels:
    team: paw
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      underscores_in_headers on;
spec:
  env:
  - name: APP_ENVIRONMENT_NAME
    value: {{ app_environment_name }}
  - name: APPRES_CMS_URL
    value: {{ appres_cms_url }}
  - name: DISABLE_FRONTEND_LOGGER
    value: "true"
  - name: LOGINSERVICE_URL
    value: {{ loginservice_url }}
  - name: ARBEIDSSOKERREGISTRERING_URL
    value: {{ arbeidssokerregistrering_url }}
  - name: DITTNAV_LINK_URL
    value: {{ dittnav_link_url }}
  - name: VEIENTILARBEID_URL
    value: {{ veientilarbeid_url }}
  - name: SYKEFRAVAER_URL
    value: {{ sykefravaer_url }}
  - name: AKTIVITETSPLAN_URL
    value: {{ aktivitetsplan_url }}
  - name: PAM_JANZZ_URL
    value: {{ pam_janzz_url }}
  - name: VEILARBPROXY_URL
    value: {{ veilarbproxy_url }}
  - name: DISABLE_SENSU_METRICS
    value: 'true'
  - name: CONTEXT_PATH
    value: /arbeid/registrering
  envFrom:
    - configmap: loginservice-idporten
  image: {{ image }}
  {{#if ingresses}}
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  {{/if}}
  liveness:
    path: /arbeid/registrering/internal/isAlive
    port: 8080
  port: 8080
  prometheus:
    enabled: true
    path: /arbeid/registrering/internal/metrics
  readiness:
    path: /arbeid/registrering/internal/isReady
    port: 8080
    initialDelay: 15
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      memory: 512Mi
  webproxy: true
  accessPolicy:
    outbound:
      rules:
        - application: pto-proxy
          namespace: pto
      external:
      {{#each externalHosts as |host|}}
         - host: {{host}}
      {{/each}}
